import { all, fork } from "redux-saga/effects";
import LoginSaga from "./loginSaga";
import AuthPhoneNumberSaga from "./authPhoneNumberSaga";
import VerifyPinSaga from "./verifyPinSaga";
import CreateUserSaga from "./createUserSaga";
import DisplayPaginatedProductsSaga from "./displayPaginatedProductsSaga";
import LoadMoreProductsSaga from "./loadMoreProductsSaga";
import GetUserByIdSaga from "./getUserByIdSaga";
import GetRecommendedProductsSaga from "./getRecommendedProductsSaga";
import RefreshProductSaga from "./refreshProductSaga";
import EditProductSaga from "./editProductSaga";
import GetProductDetailSaga from "./getProductDetailSaga";
import CreateProductSaga from "./createProductSaga";
import DeleteProductSaga from "./deleteProductSaga";
import GetDataNeededToAddPostSaga from "./getDataNeededToAddPostSaga";
import GetDataNeededToEditPostSaga from "./getDataNeededToEditPostSaga";
import GetConversationsByUserSaga from "./getConversationsByUserSaga";
import GetChatDetailSaga from "./getChatDetailSaga";
import AddTextMessageSaga from "./addTextMessageSaga";
import AddImageMessageSaga from "./addImageMessageSaga";
import GetStrangerUserSaga from "./getStrangerUserSaga";
import MarkMessagesSaga from "./markMessagesInConversationAsReadSaga";
import GoToChatSaga from "./goToChatSaga";
import GetUserAndProductsSaga from "./getUserAndProductsSaga";
import GetMyPostsSaga from "./getMyPostsSaga";
import UpdateLoginFromPersistenceSaga from "./updateLoginFromPersistanceSaga";
import GetFavoriteProductsSaga from "./getFavoriteProductsSaga";
import AddFavoriteProductSaga from "./addFavoriteProductSaga";
import RemoveFavoriteProductSaga from "./removeFavoriteProductSaga";
import ChangePasswordSaga from "./changePasswordSaga";

export default function* rootSaga() {
  yield all([fork(LoginSaga)]);
  yield all([fork(AuthPhoneNumberSaga)]);
  yield all([fork(VerifyPinSaga)]);
  yield all([fork(CreateUserSaga)]);
  yield all([fork(DisplayPaginatedProductsSaga)]);
  yield all([fork(LoadMoreProductsSaga)]);
  yield all([fork(GetUserByIdSaga)]);
  yield all([fork(GetRecommendedProductsSaga)]);
  yield all([fork(RefreshProductSaga)]);
  yield all([fork(EditProductSaga)]);
  yield all([fork(GetProductDetailSaga)]);
  yield all([fork(CreateProductSaga)]);
  yield all([fork(DeleteProductSaga)]);
  yield all([fork(GetDataNeededToAddPostSaga)]);
  yield all([fork(GetDataNeededToEditPostSaga)]);
  yield all([fork(GetConversationsByUserSaga)]);
  yield all([fork(GetChatDetailSaga)]);
  yield all([fork(GetStrangerUserSaga)]);
  yield all([fork(AddTextMessageSaga)]);
  yield all([fork(AddImageMessageSaga)]);
  yield all([fork(MarkMessagesSaga)]);
  yield all([fork(GoToChatSaga)]);
  yield all([fork(GetUserAndProductsSaga)]);
  yield all([fork(GetMyPostsSaga)]);
  yield all([fork(UpdateLoginFromPersistenceSaga)]);
  yield all([fork(GetFavoriteProductsSaga)]);
  yield all([fork(AddFavoriteProductSaga)]);
  yield all([fork(RemoveFavoriteProductSaga)]);
  yield all([fork(ChangePasswordSaga)]);
}
